"""item analysis

Revision ID: 30e40908e342
Revises: e5a2c9d17f30
Create Date: 2026-08-27 16:48:23.613080

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '30e40908e342'
down_revision: str | None = 'e5a2c9d17f30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('brand_guess', sa.String(length=120), nullable=True),
    sa.Column('colors_hex', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('color_family', sa.String(length=20), nullable=False),
    sa.Column('material', sa.String(length=80), nullable=False),
    sa.Column('fabric_weight', sa.String(length=20), nullable=False),
    sa.Column('fit', sa.String(length=60), nullable=False),
    sa.Column('cut', sa.String(length=20), nullable=False),
    sa.Column('silhouette_match', sa.String(length=120), nullable=False),
    sa.Column('pattern', sa.String(length=80), nullable=False),
    sa.Column('print_position', sa.String(length=20), nullable=False),
    sa.Column('sleeve_length', sa.String(length=40), nullable=False),
    sa.Column('neckline', sa.String(length=20), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=False),
    sa.Column('style_vibe', sa.String(length=80), nullable=False),
    sa.Column('occasion', sa.String(length=20), nullable=False),
    sa.Column('formality_score', sa.Integer(), nullable=False),
    sa.Column('wardrobe_role', sa.String(length=20), nullable=False),
    sa.Column('visual_weight', sa.String(length=20), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('temperature_range', sa.String(length=40), nullable=False),
    sa.Column('layering_suggestion', sa.String(length=20), nullable=False),
    sa.Column('separability', sa.String(length=20), nullable=False),
    sa.Column('harmonizing_colors_hex', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('harmonizing_families', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pairing_suggestions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_item_analysis_category'), 'item_analysis', ['category'], unique=False)
    op.create_index(op.f('ix_item_analysis_color_family'), 'item_analysis', ['color_family'], unique=False)
    op.create_index(op.f('ix_item_analysis_formality_score'), 'item_analysis', ['formality_score'], unique=False)
    op.create_index(op.f('ix_item_analysis_occasion'), 'item_analysis', ['occasion'], unique=False)
    op.create_index(op.f('ix_item_analysis_season'), 'item_analysis', ['season'], unique=False)
    op.create_index(op.f('ix_item_analysis_type'), 'item_analysis', ['type'], unique=False)
    op.add_column('wardrobe_items', sa.Column('analysis_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('wardrobe_items', sa.Column('analysis_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobe_items', 'analysis_error')
    op.drop_column('wardrobe_items', 'analysis_status')
    op.drop_index(op.f('ix_item_analysis_type'), table_name='item_analysis')
    op.drop_index(op.f('ix_item_analysis_season'), table_name='item_analysis')
    op.drop_index(op.f('ix_item_analysis_occasion'), table_name='item_analysis')
    op.drop_index(op.f('ix_item_analysis_formality_score'), table_name='item_analysis')
    op.drop_index(op.f('ix_item_analysis_color_family'), table_name='item_analysis')
    op.drop_index(op.f('ix_item_analysis_category'), table_name='item_analysis')
    op.drop_table('item_analysis')
    # ### end Alembic commands ###
